// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix40

import "testing"

func TestFIX40XMLNotEmpty(t *testing.T) {
	if len(FIX40XML) == 0 {
		t.Fatalf("FIX40XML is empty")
	}
}
