#!/usr/bin/env bash
# fixdecoder — FIX protocol decoder tools
# Copyright (C) 2025 Steve Clarke <stephenlclarke@mac.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# In accordance with section 13 of the AGPL, if you modify this program,
# your modified version must prominently offer all users interacting with it
# remotely through a computer network an opportunity to receive the source
# code of your version.
#
# generate_fix_xml_go.sh
# 1) Downloads FIX XMLs into ./resources
# 2) Generates fix<ver> packages embedding them
# 3) Emits chooseFixVersion.go with imports and dynamic version cases
#
set -euo pipefail
IFS=$'\n\t'

URL_BASE="https://raw.githubusercontent.com/quickfix/quickfix/master/spec"
# versions to seed download; will discover others too
VERSIONS=("40" "41" "42" "43" "44" "50" "50SP1" "50SP2" "T11")
# Base module import path for generated packages
MODULE_PATH="github.com/stephenlclarke/fixdecoder/fix"

GO_VER="1.24.3"

# 1) Download XML files
mkdir -p resources
for ver in "${VERSIONS[@]}"; do
  url="$URL_BASE/FIX${ver}.xml"
  dest="resources/FIX${ver}.xml"
  echo "Downloading $url → $dest"
  curl -sSf "$url" -o "$dest"
done

# 2) Discover all FIX*.xml in resources
mapfile -t xmlFiles < <(ls resources/FIX*.xml)
schemaVers=()
for xml in "${xmlFiles[@]}"; do
  base=$(basename "$xml" .xml)  # e.g. FIX44 or FIX50SP1
  ver=${base#FIX}                # strip leading FIX
  schemaVers+=("$ver")
done

# 3) Generate per-version Go packages
for ver in "${schemaVers[@]}"; do
  pkg="fix${ver}"
  xmlPath="resources/FIX${ver}.xml"
  outDir="fix/$pkg"
  outFile="$outDir/${pkg}.go"
  testFile="$outDir/${pkg}_test.go"

  echo "Processing $xmlPath → $outFile"
  mkdir -p "$outDir"

  escaped=$(awk '{gsub(/`/, "`\"+\"`\"+`"); print}' "$xmlPath")

  cat > "$outFile" <<EOF
// Code generated by fixdecoder from QuickFIX XML specs. DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
// This file is generated from FIX protocol XML specifications published by the
// QuickFIX project: https://github.com/quickfix/quickfix/tree/master/spec
// The QuickFIX specifications are licensed under the BSD 2-Clause License.
// Copyright (c) 2001-2015 QuickFIX. All rights reserved.
//
// The full BSD 2-Clause notice for the QuickFIX materials is included in this
// repository’s NOTICE file. This generated file is part of fixdecoder (AGPL-3.0).
//
package $pkg

// FIX${ver}XML contains the raw FIX ${ver} XML schema.
var FIX${ver}XML = \`
$escaped
\`
EOF

  # Generate minimal test to ensure schema is not empty
  cat > "$testFile" <<EOF
// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package $pkg

import "testing"

func TestFIX${ver}XMLNotEmpty(t *testing.T) {
	if len(FIX${ver}XML) == 0 {
		t.Fatalf("FIX${ver}XML is empty")
	}
}
EOF

done

# 4) Generate chooseFixVersion.go with imports and switch
out="fix/chooseFixVersion.go"
echo "Generating $out"
# Build comma-separated version list
versCSV=$(IFS=, ; echo "${schemaVers[*]}")
cat > "$out" <<EOF
// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix

import (
EOF
for ver in "${schemaVers[@]}"; do
  pkg="fix${ver}"
  printf "    %-8s \"%s/%s\"
" "$pkg" "$MODULE_PATH" "$pkg" >> "$out"
done
cat >> "$out" <<EOF
)

// chooseEmbeddedXML returns the raw XML constant for a given FIX version.
func ChooseEmbeddedXML(ver string) string {
    switch ver {
EOF
for ver in "${schemaVers[@]}"; do
  pkg="fix${ver}"
  echo "    case \"${ver}\":" >> "$out"
  echo "        return ${pkg}.FIX${ver}XML" >> "$out"
done
cat >> "$out" <<EOF
    default:
        // fallback to 44
        return fix44.FIX44XML
    }
}

// supportedFixVersions returns a comma-separated list of supported FIX versions.
func SupportedFixVersions() string {
    return "${versCSV}"
}
EOF

printf "Done.\n"