// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fixT11

import "testing"

func TestFIXT11XMLNotEmpty(t *testing.T) {
	if len(FIXT11XML) == 0 {
		t.Fatalf("FIXT11XML is empty")
	}
}
