// Code generated by generate_fix_go.sh; DO NOT EDIT.
/*
fixdecoder — FIX protocol decoder tools
Copyright (C) 2025 Steve Clarke <stephenlclarke@mac.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

In accordance with section 13 of the AGPL, if you modify this program,
your modified version must prominently offer all users interacting with it
remotely through a computer network an opportunity to receive the source
code of your version.
*/
package fix

import (
	fix40 "github.com/stephenlclarke/fixdecoder/fix/fix40"
	fix41 "github.com/stephenlclarke/fixdecoder/fix/fix41"
	fix42 "github.com/stephenlclarke/fixdecoder/fix/fix42"
	fix43 "github.com/stephenlclarke/fixdecoder/fix/fix43"
	fix44 "github.com/stephenlclarke/fixdecoder/fix/fix44"
	fix50 "github.com/stephenlclarke/fixdecoder/fix/fix50"
	fix50SP1 "github.com/stephenlclarke/fixdecoder/fix/fix50SP1"
	fix50SP2 "github.com/stephenlclarke/fixdecoder/fix/fix50SP2"
	fixT11 "github.com/stephenlclarke/fixdecoder/fix/fixT11"
)

// chooseEmbeddedXML returns the raw XML constant for a given FIX version.
func ChooseEmbeddedXML(ver string) string {
	switch ver {
	case "40":
		return fix40.FIX40XML
	case "41":
		return fix41.FIX41XML
	case "42":
		return fix42.FIX42XML
	case "43":
		return fix43.FIX43XML
	case "44":
		return fix44.FIX44XML
	case "50":
		return fix50.FIX50XML
	case "50SP1":
		return fix50SP1.FIX50SP1XML
	case "50SP2":
		return fix50SP2.FIX50SP2XML
	case "T11":
		return fixT11.FIXT11XML
	default:
		// fallback to 44
		return fix44.FIX44XML
	}
}

// supportedFixVersions returns a comma-separated list of supported FIX versions.
func SupportedFixVersions() string {
	return "40,41,42,43,44,50,50SP1,50SP2,T11"
}
