// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix43

import "testing"

func TestFIX43XMLNotEmpty(t *testing.T) {
	if len(FIX43XML) == 0 {
		t.Fatalf("FIX43XML is empty")
	}
}
