// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix42

import "testing"

func TestFIX42XMLNotEmpty(t *testing.T) {
	if len(FIX42XML) == 0 {
		t.Fatalf("FIX42XML is empty")
	}
}
