// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix44

import "testing"

func TestFIX44XMLNotEmpty(t *testing.T) {
	if len(FIX44XML) == 0 {
		t.Fatalf("FIX44XML is empty")
	}
}
