// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix50SP1

import "testing"

func TestFIX50SP1XMLNotEmpty(t *testing.T) {
	if len(FIX50SP1XML) == 0 {
		t.Fatalf("FIX50SP1XML is empty")
	}
}
