// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix41

import "testing"

func TestFIX41XMLNotEmpty(t *testing.T) {
	if len(FIX41XML) == 0 {
		t.Fatalf("FIX41XML is empty")
	}
}
