// Code generated by generate_fix_go.sh; DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com>
//
package fix50SP2

import "testing"

func TestFIX50SP2XMLNotEmpty(t *testing.T) {
	if len(FIX50SP2XML) == 0 {
		t.Fatalf("FIX50SP2XML is empty")
	}
}
